// function activateMenuItem(element, section) {
//     var items = document.querySelectorAll('.menu-item');
//     items.forEach(function(item) {
//         item.classList.remove('active');
//     });
//     element.classList.add('active');

//     var content = document.getElementById('content');
//     var contentData = {
//         'about': `<h2>Description:</h2>
//                   <p>Coralgal reefs preserve the signatures of sea-level fluctuations over Earth's history, in particular since the Last Glacial Maximum 20,000 years ago, and are used in this study to indicate that punctuated sea-level rise events are more common than previously observed during the last deglaciation. Recognizing the nature of past sea-level rises (i.e., gradual or stepwise) during deglaciation is critical for informing models that predict future vertical behavior of global oceans. Here we present high-resolution bathymetric and seismic sonar data sets of 10 morphologically similar drowned reefs that grew during the last deglaciation and spread 120 km apart along the south Texas shelf edge. Herein, six commonly observed terrace levels are interpreted to be generated by several punctuated sea-level rise events forcing the reefs to shrink and backstep through time. These systematic and common terraces are interpreted to record punctuated sea-level rise events over timescales of decades to centuries during the last deglaciation, previously recognized only during the late Holocene.</p>`,
//         'project': `<h2>Kalki Project:</h2>
//                     <p>The Kalki Project is a hypothetical initiative aimed at exploring and preserving marine life. The project focuses on understanding the impact of climate change on coral reefs and developing strategies for conservation. By using advanced technology and collaborating with marine biologists, the Kalki Project aims to create sustainable solutions for protecting marine ecosystems.</p>`,
//         'field-trips': `<h2>Field Trips:</h2>
//                        <p>Field trips are essential for hands-on learning and observation. These trips offer unique opportunities to study marine life and ecosystems in their natural habitats. Participants can engage in activities such as coral reef surveys, underwater photography, and data collection to gain a deeper understanding of marine biology.</p>`,
//         'latest-updates': `<h2>Latest Updates:</h2>
//                           <p>Stay updated with the latest news and developments in marine science. Our team regularly publishes articles and reports on recent discoveries, technological advancements, and conservation efforts. Subscribe to our newsletter to receive timely updates directly in your inbox.</p>`,
//         'collaborations': `<h2>Collaborations:</h2>
//                           <p>Collaborations with international organizations, research institutions, and local communities are key to achieving our goals. By working together, we can leverage resources, share knowledge, and implement effective conservation strategies. Join us in our mission to protect marine biodiversity.</p>`
//     };

//     content.innerHTML = contentData[section];
// }
document.addEventListener('DOMContentLoaded', function() {
    let tabs = document.querySelectorAll('.nav-link');
    let panes = document.querySelectorAll('.tab-pane');

    tabs.forEach(tab => {
        tab.addEventListener('click', function(event) {
            event.preventDefault();
            tabs.forEach(t => t.classList.remove('active'));
            panes.forEach(p => p.classList.remove('active'));

            this.classList.add('active');
            let target = this.getAttribute('href').substring(1);
            document.getElementById(target).classList.add('active');
        });
    });
});